INSERT INTO BOOKS (NAME, PRICE, SOLD) VALUES ('Java Basics', 199.00, 0);
INSERT INTO BOOKS (NAME, PRICE, SOLD) VALUES ('Spring Boot Guide', 299.00, 0);
INSERT INTO BOOKS (NAME, PRICE, SOLD) VALUES ('DBMS Concepts', 149.00, 0);
INSERT INTO BOOKS (NAME, PRICE, SOLD) VALUES ('Algorithms in Java', 249.00, 0);
INSERT INTO BOOKS (NAME, PRICE, SOLD) VALUES ('Web Development', 199.00, 0);
COMMIT;
