-- Drop existing objects safely
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE BOOKS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE BOOKS_SEQ1';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TRIGGER BOOKS_BI';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Create BOOKS table
CREATE TABLE BOOKS (
   ID NUMBER PRIMARY KEY,
   NAME VARCHAR2(255),
   PRICE NUMBER(10,2),
   SOLD NUMBER(1) DEFAULT 0
);

-- Create sequence
CREATE SEQUENCE BOOKS_SEQ1 START WITH 1 INCREMENT BY 1 NOCACHE;

-- Trigger for auto ID
CREATE OR REPLACE TRIGGER BOOKS_BI
BEFORE INSERT ON BOOKS
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
   SELECT BOOKS_SEQ1.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

-- USERS table
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE USER_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TRIGGER USERS_BI';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE USERS (
   ID NUMBER PRIMARY KEY,
   NAME VARCHAR2(255),
   PHONE VARCHAR2(20) UNIQUE,
   PREMIUM NUMBER(1) DEFAULT 0
);

CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE TRIGGER USERS_BI
BEFORE INSERT ON USERS
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
   SELECT USER_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
